version: "3.8"

services:
  backend:
    build: ./backend
    container_name: aiops_backend
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build: ./frontend
    container_name: aiops_frontend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://backend:3001
      - PROMETHEUS_URL=http://prometheus:9090
    depends_on:
      - backend
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards/aiops_dashboard.json:/var/lib/grafana/dashboards/aiops_dashboard.json
    depends_on:
      - prometheus
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager_new
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager-config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.enable-cors"

  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always

